/** Static site-level metadata and shared contact details. */
export const SITE = {
  name: "Celesnity",
  product: "Minder AI",
  description: "Generated by create next app",
  contactEmail: "start@celesnity.com",
  tagline: "Operational Intelligence For Frontline Workers",
  copyright: "© 2026 Celesnity Ltd · Minder AI · All rights reserved.",
} as const;
